#!/usr/bin/env bash
# A Bash script that displays "To infinity and beyond" with PID, stops on SIGTERM

trap "echo 'I am invincible!!!'; exit" SIGTERM

while true; do
  echo "To infinity and beyond"
  sleep 2
done

