#!/usr/bin/env bash
# This script prints messages based on iteration: 4 -> bad luck, 8 -> good luck, others -> Best School
i=1
while [ $i -le 10 ]; do
  if [ $i -eq 4 ]; then
    echo "bad luck"
  elif [ $i -eq 8 ]; then
    echo "good luck"
  else
    echo "Best School"
  fi
  ((i++))
done
